# Generated by Django 6.0.3 on 2026-07-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_tag_content_type_tag_object_id_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
