# Generated by Django 6.0.3 on 2026-07-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email_alter_usuario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
