# Generated by Django 6.0.3 on 2026-08-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADM', 'Administrador / Gestor'), ('SUP', 'Supervisor'), ('MOT', 'Motorista / Técnico')], default='MOT', max_length=3, verbose_name='Papel / Perfil'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Equipe')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_supervisionadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Responsável')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='usuarios.equipe', verbose_name='Equipe Pertencente'),
        ),
    ]
