# Generated by Django 6.0.3 on 2026-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuelrequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('km_inicial', models.IntegerField(max_length=6)),
                ('km_final', models.IntegerField(max_length=6)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('N', 'NAO_APROVADO')], default='P', max_length=1)),
            ],
        ),
    ]
