# Generated by Django 6.0.3 on 2026-03-20 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequests',
            name='km_final',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='km_inicial',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
