# Generated by Django 6.0.3 on 2026-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0003_alter_fuelrequests_km_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelrequests',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('N', 'NAO APROVADO')], default='P', max_length=1),
        ),
    ]
