# Generated by Django 6.0.3 on 2026-07-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0004_alter_fuelrequests_options_alter_fuelrequests_status'),
        ('tag', '0002_remove_tag_content_type_remove_tag_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequests',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fuelrequests', to='tag.tag'),
        ),
    ]
