# Generated by Django 6.0.3 on 2026-07-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0004_alter_fuelrequests_options_alter_fuelrequests_status'),
    ]

    operations = []