# Generated by Django 6.0.3 on 2026-07-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0005_fuelrequests_tags'),
    ]

    operations = []
