# Generated by Django 6.0.3 on 2026-07-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0006_remove_fuelrequests_tags'),
    ]

    operations = []