# Generated by Django 6.0.3 on 2026-07-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0006_remove_fuelrequests_tags'),
        ('tag', '0004_remove_tag_content_type_remove_tag_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequests',
            name='tags',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
