# Generated by Django 6.0.3 on 2026-08-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0008_remove_fuelrequests_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequests',
            name='hodometro',
            field=models.ImageField(blank=True, null=True, upload_to='hodometros/%Y/%m/', verbose_name='Foto do Hodômetro'),
        ),
    ]
