# Generated by Django 6.0.3 on 2026-08-12 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0009_fuelrequests_hodometro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequests',
            name='hodometro',
            field=models.ImageField(blank=True, null=True, upload_to='hodometros/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto do Hodômetro'),
        ),
    ]
