# Generated by Django 6.0.3 on 2026-08-14 03:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelrequests', '0010_alter_fuelrequests_hodometro'),
        ('veiculos', '0002_alter_veiculo_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelrequests',
            options={'ordering': ['-data_solicitacao', '-id'], 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AddField(
            model_name='fuelrequests',
            name='comprovante_fiscal',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='Cupom / Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='fuelrequests',
            name='supervisor_aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Responsável'),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='km_final',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='KM Final'),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='km_inicial',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='KM Inicial'),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('AG', 'APROVADO AGUARDANDO COMPROVANTE'), ('N', 'NÃO APROVADO'), ('C', 'CONCLUÍDO / COM COMPROVANTE')], default='P', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Motorista / Técnico'),
        ),
        migrations.AlterField(
            model_name='fuelrequests',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo', verbose_name='Veículo'),
        ),
    ]
